[build-system]
requires = ["setuptools>=42",
            "wheel",
            "pybind11~=2.6.1",
            "numpy>=1.7.1",
            "scipy>=1.8",
            "pandas>=1.1",
            "matplotlib>=3.3.3",
            "versioneer",
	    "statsmodels",
	    "coxdev"]
build-backend = "setuptools.build_meta"

[project]
name = "glmnet"
readme = "README.md"
description  = "GlmNet for Python"
version = "0.0.1"
license = "BSD license"
authors = "Naras Balasubrimanian, Trevor Hastie, Jonathan Taylor"
maintainers = "Naras Balasubrimanian, Trevor Hastie, Jonathan Taylor"
dependencies = ["numpy>=1.7.1", # max version for numba
               "scipy>=1.8",
               "pandas>=0.20",
               "scikit-learn>=1.2",
               "joblib",
               "statsmodels>=0.13",
	       "coxdev",
	       "pybind11",
	       "tqdm"]
classifiers = ["Development Status :: 3 - Alpha",
               "Environment :: Console",
               "Intended Audience :: Science/Research",
               "License :: OSI Approved :: BSD License",
               "Operating System :: OS Independent",
               "Programming Language :: Python",
               "Topic :: Scientific/Engineering"]
