[build-system]
requires = ["setuptools>=42",
            "wheel",
            "pybind11~=2.6.1",
            "numpy>=1.7.1",
            "scipy>=0.9",
            "pandas>=1.1",
            "matplotlib>=3.3.3",
            "versioneer",
	    "statsmodels",
	    "coxdev"]
build-backend = "setuptools.build_meta"

