# Jupyter Book configuration
# See https://jupyterbook.org/en/stable/customize/config.html

title: GLMStar Documentation
author: GLMStar Team
logo: null
execute:
  execute_notebooks: force
html:
  number_sections: true
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
repository:
  url: https://github.com/your-org/glmstar
  path_to_book: docs
  branch: main

# Sphinx configuration for autodoc
sphinx:
  extra_extensions:
    - sphinx.ext.autodoc
    - sphinx.ext.napoleon
  config:
    autodoc_default_options:
      members: true
      undoc-members: true
      show-inheritance: true