# This builds and deploys glmnet docs

name: Build docs

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs: null
    
# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel

jobs: # This workflow contains a single
      # job called "build"

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      # Install
      - name: Install dependencies 
        run: |
          pip install -r docs/requirements.txt
          pip install .

      - name: Make docs
        run: |
          cd docs
          jupyter-book build .

      # Store the output
      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: glmstar_docs
          path: docs/_build/html
          retention-days: 5

  deploy:
    runs-on: ubuntu-latest
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
      
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: glmstar_docs
        path: .
    - uses: actions/configure-pages@v5
    - uses: actions/upload-pages-artifact@v3
      with:
        path: .
    - id: deployment
      uses: actions/deploy-pages@v4