# Run tests comparing results to R

name: Compare to R

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs: null

jobs:

  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        git clone https://github.com/libigl/eigen.git --depth 5
        pip install .

    - name: Test pyglmnet
      run: |
        pip install pytest
        sudo apt-get install r-cran-glmnet
        pip install rpy2
        pytest tests


